---
title: About
output:
  html_document:
    includes:
       in_header: GA_Script.html
---

### About

This was done over a break in summer 2022 while starting to take my kids on college visits, then updated over winter break 2022-3; as I mention on the home page, while there are lots of "College Ranking" websites, they use some odd factors to rank (such as college administrators ranking each other, standardized testing scores, how many students they reject, and more for [US News and World Report](https://www.usnews.com/education/best-colleges/articles/ranking-criteria-and-weights)) while omitting things like tenure track faculty numbers, library resources, climate, and whether the state safe for LGBTQ+ students. The US federal data have information on lots of schools: I chose to present info on all the schools that are still open rather than filter for the schools just of interest to my family (my kids are not going to seminary for a Masters degree or to a school for funeral service directors any time soon, but this might be of interest to students, staff, or faculty considering those schools, so I am including them). Some schools, especially smaller ones (some have just a few dozen students) do not include all information and so these school pages might be sparse.

**If you have feedback on the site (corrections, good data sources, etc.) please go [here](https://forms.gle/C9D7WXaMDVrTm3Z3A) (and thank you!).**

There are two main types of pages on this site: one page for each institution (over 9,000 of them) and pages of degrees offered by various groupings of schools.

* The institutions have their individual data as well as comparisons with "similar" schools, where similar is based on athletic conference (for example, small liberal arts schools in Western Massachusetts), the type of the school (i.e., is it a research intensive doctoral institution). For metrics where one direction is better (lower cost is good; more faculty is good) there is a ranking versus schools in the comparison group. There are also line plots showing trends over time. If a trend is "significant" (i.e., it is not likely to be due to random chance, as assessed by fitting a linear model (and not correcting for multiple comparisons)) then there is a column indicating the slope of the trend.
* The degrees pages show degrees awarded in different fields in the most recent year available. There are many, many specific majors, so the main groups are listed at [fields_overview.html] and you can then drill down into the subfields. 

### Details of the metrics

* **Acceptance**: Percentage of undergraduate applicants who are offered admission.
* **Yield**: Percentage of people who, upon receiving the offer of admission, choose to attend.
* **First year retention**: Percentage of undergraduates who re-enroll in their second year. This can indicate they adequately like the school and are receiving support they need to be successful.
* **Transfer**: Percentage of students who transfer out from their bachelors program.
* **Graduation**: Percentage of undergraduates who graduate with a degree. Note that not all students enter an instiution with this intent: someone could take a welding class at a community college just to learn the skill without intending to get a degree in it. That said, higher graduation rate is typically a good thing.
* **Undergrad enrollment**: The number of undergraduate students (typically those seeking an associates or bachelors degree).
* **Graduate enrollment**: The number of students enrolled seeking a masters, PhD, or similar degree.


* **Degrees (of various kinds) awarded**: How many students got each degree from this college in a single year.
* **Undergrads per instructor**: Undergraduate enrollment divided by number of instructors. This does not mean the typical class size: some instructors might teach four classes, others just one; one class may have 300 students, and most others have just 10. But generally one wants a lower number so that students have more access to instructors.
* **Undergrads per tenure-track professor**: Undergraduate enrollment divided by the number of faculty on the tenure track (both tenured and pre-tenure). Tenure helps protect academic freedom: someone with tenure can be fired if they do not fulfill their duties, commit misconduct, and so forth, but they cannot (easily) be fired because the content of what they teach disagrees with what their boss thinks, their research topic annoys a major donor, and so forth. A lower number is better; the exceptions may be institutions where skilled professionals who practice a subject (a musician, an actor, a painter, and so forth) comes in to teach for a semester or a few years but with the intent for it to be short term.


* **Average net price for students with grants/scholarships**: This uses federal data for what students who are getting some sort of grant or scholarship pay *on average*. There can be *huge variation* in this: some schools charge far less for in-state than out-of-state students, some with large endowments might charge students from less wealthy families nothing but charge a lot to others, etc. It is possible that an Ivy league private university could be cheaper for some students than their local government-supported college (but far more expensive for other students), but the average price does not reflect this. Thus, this may be among the least useful items of information since it will not do a good job predicting what your family will pay. This is only reported for colleges that accept some federal support for students. Federal support comes with various requirements (prohibition of some kinds of discrimination, guidelines about handling of some kinds of alleged misconduct, and more), so a handful of colleges reject all federal support so they are not subject to one or more of these requirements. I have included a comparison to Harvard, not because Harvard is particularly expensive (its large endowment lets it award a substantial amount of aid) but to help people realize that sticker price is not the same as actual cost of attendance.


* **Tuition and fees** as a source of core revenues: What percentage of revenue comes from charging students. If an institution relies substantially on this, it can have problems if enrollment drops (it has fixed costs spread across fewer students, so it has to make cuts, and so it may attract fewer students...).
* **Investment return**: Percentage of income from investments (stocks, bonds, and so forth). Provides a buffer, but not all institutions have had wealth to build upon.
* **State/Local appropriations**: States, counties, cities may choose to invest in their residents by supporting institutions (more educated workforce, more practical skills, more understanding of our world and its history, etc.). 
* **Government grants and contracts**: Faculty often compete to get resources to support their work: a federal grant to study the effect of wildfire on deer numbers, a state grant to develop new algorithms to make self-driving cars more efficient, and so forth. These can pay for staff, support students, buy materials, cover travel, and more.
* **Private gifts, grants, and contracts**: As above, but also just donations of money or other gifts.


* **Location**: Various location statistics. 

* **Employee/Student covid vax**: At some point during the pandemic did the institution enforce a mandate that employees and/or students get vaccinated for covid? Note that regardless of whether an institution required it, anyone may still seek a vaccine: https://www.vaccines.gov/. There may be other mitigation measures as well (masking, distancing, pivoting to remote instruction) but there are no available datasets on these. This is based on reporting by [Andy Thomason and Brian O'Leary in the *Chronicle of Higher Education*](https://www.chronicle.com/blogs/live-coronavirus-updates/heres-a-list-of-colleges-that-will-require-students-to-be-vaccinated-against-covid-19).

* **Abortion**: Is abortion legal in this institution's state? In 2022, the US Supreme Court [ruled](https://en.wikipedia.org/wiki/Dobbs_v._Jackson_Women) that there was no right to abortion in the United States, leaving it to each state individually to decide on whether and how to regulate this. Some states had laws on the books regulating it, others quickly moved to pass new laws or constitutional amendments. There may also be lawsuits that prevent enforcement of some of these laws. Thus, the situation may change quickly over the next few months to years. Also, this site uses a very coarse measure of whether abortions are permitted or restricted; there is a lot of nuance (is it allowed only up to some week of pregnancy, what about to save the life of the pregnant parent, are there restrictions on leaving the state to seek an abortion) that is not captured by this.

* **Gun law stringency**: A better grade indicates more stringent laws, based on assessments by the [Giffords Law Center to Prevent Gun Violence](https://giffords.org/lawcenter/resources/scorecard/) as of Aug. 8, 2022. People who want to prioritize states with laxer gun laws should look for states with *lower* grades. Note that these are about policies at the *state* level: counties or cities may have their own laws, and institutions may create their own policies as well (for example, guns may be banned in student housing).

* **State rep support for legal contraception / same-sex and interracial marriages**: In the same ruling that overturned the Roe v. Wade precedent and thus allowed state bans of abortion, there was some discussion of overturning other precedents, such as the ones allowing same sex marriage or contraception. It is hard to predict what will happen in this area, but it may be relevant to people deciding where to be for the next several years. As an estimate of the support leaders have for these policies, the percentage of each state's delegation in the US House that voted for [US House Resolution 8404](https://www.congress.gov/bill/117th-congress/house-bill/8404) (protecting same-sex and interracial marriage) and [US House Resolution 8373](https://www.congress.gov/bill/117th-congress/house-bill/8373) (protecting the right to contraception) is now displayed. It is not a guarantee of how states will decide on these policies if it becomes a state matter, but it is at least an estimate.


* **Diversity among the faculty or students**: This uses data provided by the institutions, which is almost certainly based on individuals' self-reporting. The federal data only allows the given racial/ethnic categories and only man or woman for gender. Most other axes of diversity are not readily available. Note that people who are not residents of the US fall into the "non-resident alien" for race/ethnicity. 


* **Notes**: Individual institution pages may display a note at the top of the page triggered by various conditions. They contain explanatory notes when they appear, but so far include: 1) institutions in states where [California has decided there discriminatory laws](https://oag.ca.gov/ab1887) and so bans state-sponsored travel; 2) institutions whose administrations are currently [censured by the American Association of University Professors](https://www.aaup.org/issues/academic-freedom/whatiscensure); 3) institutions that have over a thousand students for every tenure-track faculty member (usually this means there are zero tenure-track faculty).
 
### Main sources for information

* [National Center for Education Statistics IPEDS](https://nces.ed.gov/ipeds/use-the-data): Source of much of the data on enrollment, composition of the student body and faculty, income sources, and more. Data come from mostly 2019-2020 (before the worst effects of the pandemic hit). Some data may have changed rapidly (reorganizing athletic conferences has become popular, for example).
* Walkability comes from [US EPA data](https://www.epa.gov/smartgrowth/smart-location-mapping): I've rescaled it so that 76-100% is most walkable, 52-76% is above average walkable, 29-52% is below average walkable, and 0-29% is least walkable.
* Anti-LGBTQ+ laws come from assessments made under [California bill 1887](https://oag.ca.gov/ab1887), as of July 31, 2022, which requires the California Attorney General to determine which states have laws that support discrimination against against lesbian, gay, bisexual, and transgender people and bans state-sponsored travel to those states. Note that this is a property of the state an institution is in, not any policies of the institution itself. 
* Abortion restrictions come from assessments from [World Population in Review](https://worldpopulationreview.com/state-rankings/abortion-laws-by-state) as of Aug. 8, 2022. This may change quickly.
* Gun law strictness comes from the [Giffords Law Center to Prevent Gun Violence](https://giffords.org/lawcenter/resources/scorecard/) as of Aug. 8, 2022. 
* Campus misconduct information comes from the [US Department of Education's Campus Safety and Security](https://ope.ed.gov/campussafety/#/) report. This includes data from all institutions that receive US Title IV funding, which includes most instititutions. These numbers are almost certainly a gross underestimate: see [RAINN](https://www.rainn.org/) to learn more.
* Covid vaccination requirements for students and employees comes from a [database compiled by Andy Thomason and Brian O'Leary for *The Chronicle of Higher Education*](https://www.chronicle.com/blogs/live-coronavirus-updates/heres-a-list-of-colleges-that-will-require-students-to-be-vaccinated-against-covid-19). Hopefully covid is waning, but it is a good indicator of whether a school will do a fairly basic step to keep their communities safe. Note that this field is based on text matching between a school name in IPEDS data and a school name in their database. It is also possible that a small school is missing from their database.
* Similarly, the reported misconduct field comes from matching institutions via searches to the [Academic Sexual Misconduct Database](https://academic-sexual-misconduct-database.org/), started by Dr. Julie Libarkin. This includes public cases of academic sexual misconduct (which may overlap with the misconduct on campus incidents). 
* Information on censure of a university or university system's administration comes from the [American Association of University Professors](https://www.aaup.org/), which will remove the censure once the problematic conditions are resolved.
* [WorldClim's Bioclimatic variables](https://www.worldclim.org/data/bioclim.html) are used for getting temperature and precipitation.
* Biome information comes from the [World Wildlife Fund](http://omap.africanmarineatlas.org/BIOSPHERE/data/note_areas_sp/Ecoregions_Ecosystems/WWF_Ecoregions/WWFecoregions.htm) and is accessed using Alexander Zizka and Alexandre Antonelli's [speciesgeocodeR](https://github.com/azizka/speciesgeocodeR) package ([Töpel et al. 2017](https://academic.oup.com/sysbio/article/66/2/145/2670075)).
* Map data comes from [OpenStreetMap](https://www.openstreetmap.org/).


Made by Brian O'Meara, working as an individual parent (not as part of any employment, grant, etc.). It is hosted at https://github.com/bomeara/collegetables and made using the R packages knitr, tidyverse, tarchetypes, DT, usmap, ggplot2, ggrepel, plotly, leaflet, rmarkdown, htmlTable, ggbeeswarm, speciesgeocodeR, raster, viridisLite, graphics, and stats. The page is open source, so you can give [suggestions](https://forms.gle/C9D7WXaMDVrTm3Z3A) (especially for new data sources) or even fork it; just make sure to cite the original data sources. 