---
output:
  rmdformats::readthedown:
    self_contained: false
    includes:
      in_header: GA_Script.html
params:
  degree: "nothing"
  field: "nothing"
  filtered_table: "nothing"
  definition: "nothing"
title: "`r paste0(params$degree, ': ', params$field)`"
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
source("_packages.R")
source("R/functions.R")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, results='asis'}
cat(params$definition)
```


This shows the number of graduates in the most recent year available by field. You can click on a column name to sort by it; you may also search for schools See the [Fields](fields.html) page for data on the fields available and how many schools and students offer each.



```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE, results='asis'}
filtered_table <- params$filtered_table
filtered_table$`Percent in Field` <- as.numeric(filtered_table$`Percent in Field`)
DT::datatable(filtered_table %>% dplyr::select(-UNITID) %>% dplyr::arrange(desc(`Percent in Field`)),  rownames=FALSE, escape=FALSE, extensions = c('FixedColumns', 'FixedHeader'), options=list(pageLength = 1000))
#filtered_table <- (params$filtered_table)[order(params$filtered_table$`Percent in Field`, decreasing=TRUE),]
#kable(filtered_table, escape=FALSE) %>% kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
