---
title: College Tables
output:
  html_document:
    includes:
       in_header: GA_Script.html
---

For deciding on which college to go to (as an undergraduate, graduate student, employee such as faculty member, or other) there are a lot of resources (especially for potential undergraduate students). For example, https://collegescorecard.ed.gov is created by the federal government and has great info on things like costs and expected income; there are various sites that use a secret sauce to rank colleges (what do guidance counselors think about them, how often is research from the college cited, etc.). However, as a parent, these all felt somewhat lacking: a focus on income after graduation seems sensible, for example, but a college that sends more of its students to high paying jobs on Wall Street isn't necessarily a better one than a college whose students make less money working on humanitarian issues. There are data that most sites ignore: are the libraries well-stocked and well-used; how much of a drinking culture does campus have; do faculty have academic freedom to do research and teach; how diverse are the faculty; how has the college valued safety during the covid pandemic? And issues of the environment a college is in matter: are there limits on the healthcare students can receive, is the state for or against LGBTQ+ rights, what's the weather like, is there mass transit available, and so forth. This site attempts to gather all this. It has one massive table below, but then you can go to a page on each college to get visualizations and more tables.

You can search to filter by fields: only show ones in certain states (two letter abbreviation), certain athletic leagues, by college name, etc. To search for phrases, put them in quotes. **Click on buttons to show different tables of information** (and info in one table will be used to filter the other ones). Go to the [about](about.html) page for more about the sources of the data; an explanation of some of the categories themselves follows the table.

Since much of the data come from the US federal government, this website includes only US-based schools. The rest of the planet has excellent institutions that may be a better placement for some.

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
source("_packages.R")
source("R/functions.R")

all_colleges <- data.frame()

try(load("all_colleges.rda"), silent=TRUE)


if(nrow(all_colleges)>0) {

	all_colleges$Name <- rownames(all_colleges)
	for (college_index in sequence(nrow(all_colleges))) {
		all_colleges$Name[college_index] <- paste0("<a href='https://collegetables.info/", utils::URLencode(gsub(" ", "", all_colleges$Name[college_index])),  ".html'>", all_colleges$Name[college_index], "</a>")
	}
	Overview <- c("Name", "Institution type", "Institution sector" , "Avg net price for students with grants/scholarships","Undergraduate enrollment",  "Graduate enrollment", "Athletic conference" )

	Admissions_and_outcomes <- c("Admission", "Yield", "First year retention", "Graduation")

	Location <- c("City", "State", "Type", "Mass transit", "Walkability", "Local ecology", "Local biome", "Annual precipitation", "Warmest month max temp", "Coldest month min temp")

	Safety <- c("Abortion", "Employee covid vax", "Student covid vax", 
"Abortion", "Gun law stringency", "State rep support for legal contraception", "State rep support for same-sex and interracial marriages")

	AcademicResources <- c("Undergrads per instructor", "Undergrads per tenure-track professor", "Number of physical books", "Number of physical media", "Number of digital/electronic books", 
"Total library circulations (physical and digital/electronic)", 
"Average library loans (physical) per student or faculty member", 
"Average library loans (physical + digital) per student or faculty member")

	Misconduct <- c("Liquor discipline ", "Liquor arrest ", "Drug discipline ", "Drug arrest ", 
"Weapon discipline ", "Weapon arrest ", "Reported rape ", "Reported fondling ")

	Finances <- c("Endowment assets per FTE", 
"Equity ratio", "Tuition and fees", "Investment return", "State appropriations", 
"Local appropriations", "Government grants and contracts", "Private gifts  grants  and contracts")

	Degrees <- c("Associates degrees awarded", 
"Bachelors degrees awarded", "Masters degrees awarded", "Doctorates awarded")

AllFields <- c(Overview, Admissions_and_outcomes, Location, Safety, AcademicResources, Misconduct, Finances, Degrees)



	all_colleges_cleaned <- all_colleges[,AllFields]
	for (col_index in sequence(ncol(all_colleges_cleaned))) {
			all_colleges_cleaned[,col_index] <- gsub('$NaN', '', all_colleges_cleaned[,col_index])
	}

	
	
	GetMatchingColumnsInOverview <- function(to_find) {
		return(-1+match(to_find, colnames(all_colleges_cleaned)))	
	}

	GetNotMatchingColumnsInOverview <- function(to_find) {
		unmatched <- setdiff(colnames(all_colleges_cleaned), unique(c("Name", to_find)))
		return(-1+match(unmatched, colnames(all_colleges_cleaned)))	
	}



	DT::datatable(
		as.matrix(all_colleges_cleaned), rownames=FALSE, escape=FALSE, extensions = c('Buttons', 'FixedColumns', 'FixedHeader'),
			options=(
				list(
					fixedColumns = list(leftColumns=1),
					columnDefs = list(
 						list(targets = c(7:(ncol(all_colleges_cleaned)-1)), visible = FALSE)
 					),
					dom = 'Bfrtip',
					pageLength = 100,
		 			fixedHeader = TRUE,
					buttons = list(
						list(
							extend= "colvisGroup", 
							text="Overview", 
							show=c(0, GetMatchingColumnsInOverview(Overview)),
							hide=GetNotMatchingColumnsInOverview(Overview)
						),
						list(
							extend= "colvisGroup",
							text="Admissions & Outcomes",
							show=c(0, GetMatchingColumnsInOverview(Admissions_and_outcomes)), 
							hide=GetNotMatchingColumnsInOverview(Admissions_and_outcomes)
						),
						list(
							extend= "colvisGroup",
							text="Location",
							show=c(0, GetMatchingColumnsInOverview(Location)), 
							hide=GetNotMatchingColumnsInOverview(Location)
						),
						list(
							extend= "colvisGroup",
							text="Academic resources",
							show=c(0, GetMatchingColumnsInOverview(AcademicResources)), 
							hide=GetNotMatchingColumnsInOverview(AcademicResources)
						),
						list(
							extend= "colvisGroup",
							text="Safety",
							show=c(0, GetMatchingColumnsInOverview(Safety)), 
							hide=GetNotMatchingColumnsInOverview(Safety)
						),
						list(
							extend= "colvisGroup",
							text="Misconduct",
							show=c(0, GetMatchingColumnsInOverview(Misconduct)), 
							hide=GetNotMatchingColumnsInOverview(Misconduct)
						),
						list(
							extend= "colvisGroup",
							text="Finances",
							show=c(0, GetMatchingColumnsInOverview(Finances)), 
							hide=GetNotMatchingColumnsInOverview(Finances)
						),
						list(
							extend= "colvisGroup",
							text="Degrees",
							show=c(0, GetMatchingColumnsInOverview(Degrees)), 
							hide=GetNotMatchingColumnsInOverview(Degrees)
						)
					)
				)
			)
		)


}
```